-- SELECT * FROM HR.EMPLOYEES

-- SELECT COUNT(*) FROM HR.EMPLOYEES

-- SELECT COUNT(DEPARTMENT_ID) AS DEPT,COUNT(DISTINCT DEPARTMENT_ID) AS UNIQ_DEPT FROM HR.EMPLOYEES

-- DESCRIPTIVE STATISITCS,AGGREGATE FUNCTIONS
-- SELECT AVG(SALARY),
-- MIN(SALARY) AS MIN,
-- MAX(SALARY) AS MAX,
-- MEDIAN(SALARY) AS MEDIAN,
-- STDDEV(SALARY) AS STD_DIV,
-- VARIANCE(SALARY) AS VAR
-- FROM HR.EMPLOYEES


-- SELECT DEPARTMENT_ID AS DEPT_ID,COUNT(*) AS COUNT FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID 

-- SELECT DEPARTMENT_ID AS DEPT_ID, AVG(SALARY) AS AVERAGE FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID


-- FIND THE UNIQUE JOB IDS FOR EACH DEPARTMENT ID

-- SELECT DEPARTMENT_ID AS DEPT_ID, COUNT(DISTINCT JOB_ID) AS UNIQUE_JOB_ID FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID

-- SELECT DEPARTMENT_ID,SUM(SALARY) FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID;
-- SELECT DEPARTMENT_ID,AVG(SALARY) FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID;
-- SELECT DEPARTMENT_ID,MIN(SALARY) FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID;
-- SELECT DEPARTMENT_ID,MAX(SALARY) FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID;
-- SELECT DEPARTMENT_ID,STDDEV(SALARY) FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID;
-- SELECT DEPARTMENT_ID,VARIANCE(SALARY) FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID;

-- SELECT
--     DEPARTMENT_ID,
--     SUM(SALARY)      AS TOTAL_SALARY,
--     AVG(SALARY)      AS AVG_SALARY,
--     MIN(SALARY)      AS MIN_SALARY,
--     MAX(SALARY)      AS MAX_SALARY,
--     STDDEV(SALARY)   AS SALARY_STDDEV,
--     VARIANCE(SALARY) AS SALARY_VARIANCE
-- FROM
--     HR.EMPLOYEES
-- GROUP BY
--     DEPARTMENT_ID


-- SELECT DEPARTMENT_ID,COUNT(*) FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID HAVING COUNT(*)>=5

-- SHOW DEPARTMENTS THAT HAS AVG SALARY GREATER THAN 50000

-- SELECT DEPARTMENT_ID,AVG(SALARY) FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID HAVING AVG(SALARY) BETWEEN 4000 AND 5000


-- SELECT DEPARTMENT_ID,AVG(SALARY) FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID HAVING AVG(SALARY)>5000


-- GET THE DEPARTMENT IDS WHERE MORE THAN 3 JOB_ID ROLES ARE EXISTS

-- SELECT DEPARTMENT_ID,COUNT(DISTINCT JOB_ID) FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID HAVING COUNT(DISTINCT JOB_ID)>=3


-- SELECT DEPARTMENT_ID,COUNT(DISTINCT JOB_ID) FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID

--SELECT EMPLOYEE_ID,SALARY FROM HR.EMPLOYEES ORDER BY SALARY DESC


-- SELECT
--     DEPARTMENT_ID,
--     SUM(SALARY) AS TOTALSALES
-- FROM
--     HR.EMPLOYEES
-- GROUP BY
--     DEPARTMENT_ID
-- HAVING
--     SUM(SALARY) > 100000
-- ORDER BY
--     TOTALSALES ASC