-- SELECT UPPER('DATA'), LOWER('DATA'), LENGTH('DATA'), INITCAP('DATA ENGINEERING'),
-- LTRIM(' DATA '), RTRIM(' DATA ') FROM DUAL

-- ## ADDS O'S TILL THE 5TH PLACE FROM LEFT
-- SELECT LPAD('123',5,'0') FROM DUAL

-- ## ADD O'S TILL THE 8TH PLACE FROM RIGHT, IF THE LENGTH IS GREATER THAN 8, 
-- ## IT'LL BE REMOVED TILL THE 8TH PLACE FROM RIGHT
-- SELECT RPAD('123456',8,'0') FROM DUAL

-- ## TRIMS THE SPCAES BEFORE AND AFTER THE VALUE
-- SELECT TRIM('   DATA   ') FROM DUAL

-- ## REPLACES 'SCIENCE' FROM 'DATA SCIENCE' WITH 'ENGINEERING'
-- SELECT REPLACE ('DATA SCIENCE', 'SCIENCE', 'ENGINEERING') FROM DUAL

-- ## CONVERTS THE VALUE AS AN INTEGER
-- SELECT ABS(-10) AS ABSOLUTE_VALUE FROM DUAL

-- ## REMOVES THE DECIMAL
-- SELECT FLOOR(12.45) FROM DUAL

-- ## ROUNDS THE MENTIONED DECIMAL PLACE 
-- SELECT ROUND(12.345, 2) AS ROUNDED_VALUE FROM DUAL
-- SELECT ROUND(12.345, 0) AS ROUNDED_VALUE FROM DUAL

-- ## RETURN THE REMIANDER
-- SELECT MOD(10, 3) AS REMAINDER FROM DUAL

-- ## POWER FUNCTION
-- SELECT POWER(2, 3) AS POWER_VALUE FROM DUAL

-- ## SQUART ROOT FUNTION
-- SELECT SQRT(25) AS SQUARE _ROOT FROM DUAL

-- ## RETURNS THE SIGN OF THE NUMBER AS + OR -
-- SELECT SIGN(-15) AS SIGN_VALUE FROM DUAL

-- ## RETURNS E^X
-- SELECT EXP(1) AS EXPONENTIAL_VALUE FROM DUAL

-- ## RETURNS THE NATURAL LOGARITHM (LOG BASE E) OF A NUMBER
-- SELECT LN(10) AS NATURAL_LOG FROM DUAL

-- ## LOG: RETURNS THE LOGARITHM OF A NUMBER TO A SPECIFIED BASE
-- SELECT LOG(10, 1000) AS LOG_VALUE FROM DUAL

-- ## RETURNS THE GREATEST VALUE
-- SELECT GREATEST(10,20,30,40) FROM DUAL

-- ## RETURNS THE SMALLEST VALUE
-- SELECT LEAST(10,20,30,40) FROM DUAL

-- ## RETURNS THE TRIGINOMETRIC VALUES
-- SELECT SIN(0),COS(0),TAN(0),ATAN(0),ACOS(0),ASIN(0) FROM DUAL


-- ## SYSTEM FUNCTIONS
-- SELECT SYSDATE FROM DUAL

-- SELECT SYSTIMESTAMP FROM DUAL

-- SELECT CURRENTDATE FROM DUAL