-- DECLARE
--     STUDENT_NAME VARCHAR2(50):='EDUKRON';
-- BEGIN
--     DBMS_OUTPUT.PUT_LINE('HELLO ' || STUDENT_NAME);
-- END;

-- ### NUMBER : NUMBER(10),NUMBER(10,2)
-- ### VARCHAR2 : MIX NUMBERS AND CHARACTERS ( MAX 32767 BYTES IN PLSQL,4000 IN SQL)
-- ### TRUE, FALSE 
-- ### DATE, TIME, TIMESTAMP
-- ###

-- RECORD ()


-- DECLARE
--     TYPE EMP_RECORD IS RECORD (
--      EMP_ID NUMBER, EMP_NAME VARCHAR2(20),EMP_SALARY NUMBER(10,2));
--       EMP EMP_RECORD;
-- BEGIN
--     EMP.EMP_ID:=100;
--     EMP.EMP_NAME:='EDUKRON';
--     EMP.EMP_SALARY:=20000;
--     DBMS_OUTPUT.PUT_LINE(EMP.EMP_NAME || ' '|| EMP.EMP_ID || ' ' ||EMP.EMP_SALARY);
-- END;





-- SELECT FIRST_NAME FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=101;




-- DECLARE
--     EMP_NAME VARCHAR2(100);
--     SALARY NUMBER;
-- BEGIN
--     SELECT FIRST_NAME,SALARY INTO EMP_NAME,SALARY FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=101;
--     DBMS_OUTPUT.PUT_LINE(EMP_NAME||SALARY);
-- END;


-- DECLARE
--     EMP_STATUS  VARCHAR2(20);
-- BEGIN
--     SELECT CASE WHEN SALARY>50000 THEN 'HIGH' 
--     ELSE 'LOW' END
--     INTO EMP_STATUS FROM HR.EMPLOYEES  WHERE EMPLOYEE_ID=101;
--     DBMS_OUTPUT.PUT_LINE(EMP_STATUS);
-- END;





-- DECLARE
--     NUMBER_OF_ROWS NUMBER;
-- BEGIN
--     SELECT COUNT(*) INTO NUMBER_OF_ROWS FROM HR.EMPLOYEES;
--     DBMS_OUTPUT.PUT_LINE(NUMBER_OF_ROWS);
-- END ;

-- RANGE
-- DECLARE
--     SALARY_RANGE NUMBER;
-- BEGIN
--     SELECT MAX(SALARY)-MIN(SALARY) INTO SALARY_RANGE FROM HR.EMPLOYEES ;
--     DBMS_OUTPUT.PUT_LINE(SALARY_RANGE);
-- END;


-- DECLARE
--     MIN_SALARY NUMBER;
--     MAX_SALARY NUMBER;
-- BEGIN
--     SELECT MAX(SALARY),MIN(SALARY) INTO MAX_SALARY,MIN_SALARY FROM HR.EMPLOYEES ;
--     DBMS_OUTPUT.PUT_LINE(MAX_SALARY-MIN_SALARY);
-- END;



-----------------------
-- BEGIN

-- 	FOR I IN 1..5 LOOP
-- 		DBMS_OUTPUT.PUT_LINE(I);
-- 	END LOOP;
-- END;



-- DECLARE
--     X NUMBER := 1; 
-- BEGIN
--     WHILE X < 5 LOOP  
--         DBMS_OUTPUT.PUT_LINE(X);  
--         X := X + 1; 
--     END LOOP;
-- END;