-- SELECT * FROM HR.EMPLOYEES *

-- SELECT EMPLOYEE_ID,FIRST_NAME,SALARY FROM HR.EMPLOYEES WHERE SALARY>10000

-- DUMMY TABLE - DUAL, CAN BE USED FOR ANY FUNCTIONAL DEMO ****

-- ##OPERATORS##
-- ARITHMETIC OPERATOR ##
-- SELECT 10+5 AS ADDITION,
-- 10-5 AS SUBSTITUTE,
-- 10*5 AS MULTIPLICATION,
-- 10/5 AS DIVISION FROM DUAL

-- COMPARISION OPERATOR ##
-- SELECT * FROM HR.EMPLOYEES WHERE SALARY>10000
-- SELECT * FROM HR.EMPLOYEES WHERE SALARY<10000
-- SELECT * FROM HR.EMPLOYEES WHERE SALARY>=10000
-- SELECT * FROM HR.EMPLOYEES WHERE SALARY>=10000
-- SELECT * FROM HR.EMPLOYEES WHERE SALARY<>10000
-- SELECT * FROM HR.EMPLOYEES WHERE SALARY=10000

-- LOGICAL OPERATOR (AND OR NOT)##
-- SELECT * FROM HR.EMPLOYEES WHERE SALARY>2000 AND DEPARTMENT_ID=90
-- SELECT * FROM HR.EMPLOYEES WHERE SALARY>2000 OR DEPARTMENT_ID=90
-- SELECT * FROM HR.EMPLOYEES WHERE NOT DEPARTMENT_ID=90

-- CONCATENATION OPERATOR ##
-- SELECT FIRST_NAME || ' ' || LAST_NAME FULL_NAME FROM HR.EMPLOYEES

-- BETWEEN, LIKE OPERATOR ##
-- SELECT * FROM HR.EMPLOYEES WHERE SALARY BETWEEN 10000 AND 30000
-- SELECT 100 BETWEEN 5 AND 15 AS RESULT FROM DUAL
-- SELECT * FROM HR.EMPLOYEES WHERE FIRST_NAME LIKE 'B%'
-- SELECT * FROM HR.EMPLOYEES WHERE FIRST_NAME LIKE '%a'
-- SELECT * FROM HR.EMPLOYEES WHERE FIRST_NAME LIKE '%am%'
-- SELECT * FROM HR.EMPLOYEES WHERE FIRST_NAME LIKE 'B%'

-- IN OPERATOR ##
-- SELECT * FROM HR.EMPLOYEES WHERE DEPARTMENT_ID IN (50,60,70)